# config for server address and port
# address - str. For example "192.168.55.1"
# port - int. For example 50000
# remember, that server and client should be in one local network

server:
  address: ""
  port:
